image: node:8.11.3

stages:
  - ver
  - tests
  - deploy

ver:
  stage: ver
  script:
    - node --version
    - whoami
  tags:
    - docker

all_tests:
  stage: tests
  script:
   - yarn install
   - yarn run test
  tags:
    - docker


deploy_staging:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/node-ci-staging.git
    - git push heroku master
    - echo "Deployed to staging server"
  environment:
    name: staging
    url: https://node-ci-staging.herokuapp.com/
  only:
    - master
  tags:
    - docker

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/node-ci-prod.git
    - git push heroku master
    - echo "Deployed to production server"
  environment:
    name: production
    url: https://node-ci-prod.herokuapp.com/
  when: manual
  only:
    - master
    - git push heroku master
  tags:
    - docker
  